[package]
name = "sldrepair"
version = "0.1.0"
authors = ["Aaron Haley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.8"
dialoguer = "0.8"
console = "0.14"